# Generated by Django 5.2.6 on 2025-09-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='contact',
        ),
    ]
